version: "3"
services:
  miner-discovery:
    image: navin3d/miner-discovery
    ports:
      - "8010:8010"
    restart: "always"
  miner-orderer:
    build:
      context: ./miner/miner_orderer_peer
      dockerfile: Dockerfile
    environment:
      PORT: "8001"
      HOST: "192.168.29.43"
      EUREKA_HOST: "miner-discovery"
    restart: "always"
    ports:
      - "8001:8000"
    depends_on:
      - miner-discovery
